config:
  target: "http://localhost:2000" 
  phases:
    - duration: 5                  
      rampTo: 100                
  engines:
    socketio: {}                
scenarios:
  - engine: "socketio"
    flow:
      - emit:
          channel: "createResult"  
          data:
            questionId: 4          
            answer: "Answer 1"  


